// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_get_contact_map
IntegerMatrix rcpp_get_contact_map(DataFrame hybrids, int gene_A_size, int gene_B_size);
RcppExport SEXP _toscatools_rcpp_get_contact_map(SEXP hybridsSEXP, SEXP gene_A_sizeSEXP, SEXP gene_B_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type hybrids(hybridsSEXP);
    Rcpp::traits::input_parameter< int >::type gene_A_size(gene_A_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type gene_B_size(gene_B_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_contact_map(hybrids, gene_A_size, gene_B_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_toscatools_rcpp_get_contact_map", (DL_FUNC) &_toscatools_rcpp_get_contact_map, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_toscatools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
