# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get contact map using Rcpp
#'
#' This function gets the contact map from a given DataFrame of hybrids. It uses Rcpp for faster computation.
#' It loops through each hybrid, gets the start and end points of the left and right genes, and increments the corresponding cells in the contact map.
#'
#' @param hybrids The DataFrame of hybrids.
#' @param gene_A_size The size of gene A.
#' @param gene_B_size The size of gene B.
#' @return An IntegerMatrix representing the contact map.
#'
#' @export
rcpp_get_contact_map <- function(hybrids, gene_A_size, gene_B_size) {
    .Call(`_toscatools_rcpp_get_contact_map`, hybrids, gene_A_size, gene_B_size)
}

